server:
  port: 9080
  servlet:
    context-path: "/pruebaTecnica"
spring:
  application:
    name: "PruebaTecnica"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    #url, username and password de la base de datos
    url: "jdbc:mysql://localhost:3306/prueba?useSLL=false&serverTimezone=UTC&useLegacyDateTimeCode=false"
    username: "root"
    password: ""
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    show-sql: true
    databasePlatform: "org.hibernate.dialect.MySQL5Dialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
